### PR TITLE
Steel Ingot Recipe and Silver Wire Fixes

### LINKED ISSUE #4: Steel Ingot clear_craft Comment
For some reason a bug from the original Elepower pack was carried over into this repository. The `core.clear_craft` for iron lump -> steel ingot was in a comment, so the function wasn't executed. I already have a temporary fork that uncomments the function.

### LINKED ISSUE #6: Silver Wire in copper group
For some reason, the silver wire in elepower_compat/mods/basic_materials.lua has copper listed in the groups instead of silver.

### PR DESCRIPTION
**Pull request by DustyDave961**
Fixes #4. Fixes #6. Why was the iron lump -> steel ingot recipe clear function in a comment?

### CODE REVIEW

File: elepower_dynamics/crafting.lua [hunk 1]
```diff
@@ -8,7 +8,7 @@ local ept = ele.external.tools
 ---------------
 
 -- Remove iron_lump -> steel_ingot, because dynamics adds iron ingot
--- minetest.clear_craft({type = "cooking", output = epi.steel_ingot})
+minetest.clear_craft({type = "cooking", output = epi.steel_ingot})
```
Comment (LunaSquee) [inline elepower_dynamics/crafting.lua]:
```suggestion
if epi.steel_ingot ~= "" then
    minetest.clear_craft({type = "cooking", output = epi.steel_ingot})
end
```
Required for non-MTG compliance.

**Review by LunaSquee — CHANGES_REQUESTED** [review]
